subscription($id: ID!) {
  updateOrder(id: $id) {
    id
    status
    totalPrice
    lineItems {
        price
        quantity
        sku
        productName
        variantNames {
            name
        }
    }
  }
}
