mutation($id: ID!, $email: String!) {
  addCartToCustomer(email: $email, id: $id) {
    order {
      id
      totalPrice
      lineItems {
        sku
        price
        quantity
      }
      customer {
        email
      }
    }
  }
}