mutation($lineItem: LineItemInput!, $id: ID) {
    addItemToCart(
        id: $id,
        lineItem: $lineItem
    ) {
        id
        status
        totalPrice
        lineItems {
            price
            quantity
            sku
            productName
            variantNames {
                name
                presentation
            }
        }
    }
}
